apiVersion: v2
name: srm
description: Software Risk Manager
type: application
icon: https://synopsys.com/content/dam/synopsys/sig-assets/images/icons/synopsys-codedx.svg
version: 1.34.0
appVersion: "v2024.9.2"

dependencies:
- name: mariadb
  version: 7.6.0
  repository: https://stevesnps.github.io/srm-k8s-test
  condition: features.mariadb
- name: cnc
  version: "2024.3.0"
  repository: https://sig-repo.synopsys.com/artifactory/sig-cloudnative
  condition: features.scanfarm
- name: argo-workflows
  version: 0.41.4
  repository: https://argoproj.github.io/argo-helm
  condition: features.to
- name: minio
  version: 3.3.0
  repository: https://stevesnps.github.io/srm-k8s-test 
  condition: features.minio
