{{- if (not .Values.web.webSecret) -}}
{{- $default := lookup "v1" "Secret" .Release.Namespace (include "srm-web.default.web.secret" .) -}}
{{- $adminPassword := dig "data" "admin-password" (randAlphaNum 10 | b64enc) $default | b64dec -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "srm-web.default.web.secret" . | quote }}
  labels:
    {{- include "srm-web.labels" . | nindent 4 }}
type: Opaque
data:
  # lookup requires cluster access, so a disconnected context (e.g., dry-run, template) has no password reuse with generated password(s)
  admin-password: {{ $adminPassword | b64enc }}
{{- end -}}