{{- if .Values.features.scanfarm -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "srm-sf.svc-job" . | quote }}
  labels:
    {{- include "srm-sf.svc-job-labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      labels:
        {{- include "srm-sf.svc-job-labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "srm-web.serviceAccountName" . | quote }}
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      {{- if .Values.web.nodeSelector }}
      nodeSelector:
      {{- toYaml .Values.web.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.web.tolerations }}
      tolerations:
      {{- toYaml .Values.web.tolerations | nindent 8 }}
      {{- end }}
      restartPolicy: Never
      containers:
      - name: configuration-job
        image: "{{ .Values.web.image.registry }}/{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
        command:
          - /bin/bash
          - -c
          - |
{{ include "srm-web.key-job" . | indent 12 }}
        volumeMounts:
        - name: web-secret
          mountPath: {{ include "srm-web.admin.password.path" . }}
          subPath: {{ include "srm-web.admin.password.filename" . }}
      volumes:
      - name: web-secret
        secret:
          secretName: {{ include "srm-web.web.secret" . | quote }}
{{- end -}}