{{- if .Values.features.scanfarm -}}
{{- $saName := (include "srm-web.serviceAccountName" .) | quote -}}
{{- $rName := (include "srm-web.rolename" .) | quote -}}
{{- $rbName := (include "srm-web.rolebindingname" .) | quote -}}

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $rName }}
  labels:
    {{- include "srm-web.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create", "update", "patch"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $rbName }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "srm-web.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $rName }}
subjects:
- name: {{ $saName }}
  kind: ServiceAccount
  namespace: {{ .Release.Namespace | quote }}
{{- end -}}