apiVersion: v1
kind: Service
metadata:
  name: {{ include "srm-web.fullname" . }}
  labels:
    {{- include "srm-web.labels" . | nindent 4 }}
  annotations:
{{ toYaml .Values.web.service.annotations | indent 4 }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - name: {{ .Values.web.service.port_name | default "http" }}
      protocol: TCP
      port: {{ .Values.web.service.port }}
      {{- if .Values.web.tlsSecret }}
      targetPort: 8443
      {{- else }}
      targetPort: 8080
      {{- end }}
  selector:
    {{- include "srm-web.selectorLabels" . | nindent 4 }}
