{{- if .Values.features.to -}}
{{- if and (not .Values.web.toSecret) (not .Values.to.toSecret) -}}
{{- $default := lookup "v1" "Secret" .Release.Namespace (include "srm-to.default.key.secret" .) -}}
{{- $toKey := dig "data" "api-key" (randAlphaNum 10 | b64enc) $default | b64dec -}}
{{- $toKeyProp := (printf "tws.api-key = \"\"\"%s\"\"\"" $toKey) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "srm-to.default.key.secret" . | quote }}
  labels:
    {{- include "srm-to.labels" . | nindent 4 }}
type: Opaque
data:
  # lookup requires cluster access, so a disconnected context (e.g., dry-run, template) has no password reuse with generated password(s)
  api-key: {{ $toKey | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "srm-web.default.web.key.secret" . | quote }}
  labels:
    {{- include "srm-web.labels" . | nindent 4 }}
type: Opaque
data:
  # lookup requires cluster access, so a disconnected context (e.g., dry-run, template) has no password reuse with generated password(s)
  to-key.props: {{ $toKeyProp | b64enc }}
{{- end -}}
{{- end -}}