{{- if .Values.features.minio -}}
{{- if (not .Values.minio.global.minio.existingSecret) -}}
{{- $default := lookup "v1" "Secret" .Release.Namespace (include "srm-to.default.minio.secret" .) -}}
{{- $accessKey := dig "data" "access-key" (randAlphaNum 10 | b64enc) $default | b64dec -}}
{{- $secretKey := dig "data" "secret-key" (randAlphaNum 10 | b64enc) $default | b64dec -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "srm-to.default.minio.secret" . | quote }}
  labels:
    {{- include "srm-to.labels" . | nindent 4 }}
type: Opaque
data:
  # lookup requires cluster access, so a disconnected context (e.g., dry-run, template) has no password reuse with generated password(s)
  access-key: {{ $accessKey | b64enc }}
  secret-key: {{ $secretKey | b64enc }}
{{- end -}}
{{- end -}}