{{- if .Values.features.to -}}
{{- if .Values.to.podDisruptionBudget.enabled -}}
{{- if $.Capabilities.APIVersions.Has "policy/v1/PodDisruptionBudget" }}
apiVersion: policy/v1
{{- else }}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "srm-to.fullname" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
spec:
{{- $minAvailable := .Values.to.podDisruptionBudget.minAvailable -}}
{{- $maxUnavailable := .Values.to.podDisruptionBudget.maxUnavailable -}}

{{- if or (kindIs "int64" $minAvailable) (kindIs "float64" $minAvailable) }}     {{/* use kindIs to distinguish between an empty value and 0 */}}
  minAvailable: {{ $minAvailable }}
{{- else if $minAvailable }}  
  minAvailable: {{ $minAvailable | quote }}
{{- end }}

{{- if or (kindIs "int64" $maxUnavailable) (kindIs "float64" $maxUnavailable) }} {{/* use kindIs to distinguish between an empty value and 0 */}}
  maxUnavailable: {{ $maxUnavailable }}
{{- else if $maxUnavailable }}  
  maxUnavailable: {{ $maxUnavailable | quote }}
{{- end }}
  selector:
    matchLabels:
      {{- include "srm-to.selectorLabels" . | nindent 6 }}
{{- end -}}
{{- end -}}