{{- if .Values.features.to -}}
{{- $saName := (include "srm-to.serviceAccountName" .) | quote -}}
{{- $hookRoleName := (include "srm-to.predelete.rolename" .) | quote -}}
{{- $hookRoleBindingName := (include "srm-to.predelete.rolebindingname" .) | quote -}}

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $hookRoleName }}
  labels:
    {{- include "srm-to.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "delete"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "delete"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $hookRoleBindingName }}
  labels:
    {{- include "srm-to.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $hookRoleName }}
subjects:
- name: {{ $saName }}
  kind: ServiceAccount
  namespace: {{ .Release.Namespace | quote }}
{{- end -}}