{{- if .Values.features.to -}}

{{- $svcRoleName := (include "srm-to.rolename" .) | quote -}}

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $svcRoleName }}
  labels:
    {{- include "srm-to.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "update", "patch", "delete", "watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get"]
- apiGroups: ["argoproj.io"]
  resources: ["workflows"]
  verbs: ["get", "list", "create", "delete", "patch"]
- apiGroups: ["argoproj.io"]
  resources: ["workflowtaskresults"]
  verbs: ["create", "patch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ (include "srm-to.rolebindingname" .) | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "srm-to.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $svcRoleName }}
subjects:
- name: {{ (include "srm-to.serviceAccountName" .) | quote }}
  kind: ServiceAccount
  namespace: {{ .Release.Namespace | quote }}

{{- end -}}