{{- if .Values.features.to -}}
{{- if .Values.to.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "srm-to.serviceAccountName" . }}
  labels:
    {{- include "srm-to.labels" . | nindent 4 }}
  {{- with .Values.to.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}